---
  - name: Ensure ZSH is installed
    homebrew:
      name: "zsh"
      state: present
    notify:
      - Clear homebrew cache

  - name: Ensure iTerm is installed
    homebrew:
      name: "iterm2"
      state: present
    notify:
      - Clear homebrew cache

- name: Instal oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ ansible_env.HOME + '/.oh-my-zsh' }}"
    update: yes

- name: Configure oh-my-zsh
  template:
    src: "zshrc.j2"
    dest: "{{ ansible_env.HOME + '/.zshrc' }}"

- name: Setting default shell
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_user_id }}"

- name: Ensure fonts are installed.
  get_url:
    url: "{{ item.url }}"
    dest: "~/Library/Fonts"
  with_items: "{{ iterm2_fonts }}"
  when: iterm2_fonts is defined

- name: Ensure shell integration is installed.
  shell: curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
  args:
    warn: no
